export const IDS = {
  LOGO: "logo",
  NO_SCHEMAS_FOUND: "no-schemas-found",
  schema: {
    page: "schema-page",
    list: "schema-list",
    render: "schema-render",
  },
  trace: {
    view: "trace-view",
    header: "trace-header",
    list: "trace-list",
    editor: "trace-editor",
    query: "trace-query",
    variables: "trace-variables",
    expand_variables: "trace-expand-variables",
    switch_view: "trace-switch-view",
    json_viewer: "trace-json-viewer",
    pill: "trace-pill",
  },
  trace_list: {
    view: "trace-list-view",
    table: "trace-list-table",
  },
  trace_viewer: {
    view: "trace-viewer-view",
    not_found: "trace-viewer-not-found",
  },
  dashboard: {
    page: "dashboard-page",
    logo: "dashboard-logo",
  },
  sidebar: {
    logo: "sidebar-logo",
    view: "sidebar-view",
    icons: {
      view: "sidebar-icons-view",
      schemas: "sidebar-schemas",
      config: "sidebar-config",
      login: "sidebar-login",
      history: "sidebar-history",
      favourites: "sidebar-favourites",
      npm: "sidebar-npm",
      github: "sidebar-github",
      info: "sidebar-info",
    },
    views: {
      schemas: "sidebar-schemas-view",
      config: "sidebar-config-view",
      login: "sidebar-login-view",
      history: "sidebar-history-view",
      favourites: "sidebar-favourites-view",
      info: "sidebar-info-view",
    },
  },
};
